package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePluginConfigItemParams creates a new DeletePluginConfigItemParams object
// with the default values initialized.
func NewDeletePluginConfigItemParams() *DeletePluginConfigItemParams {
	var ()
	return &DeletePluginConfigItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePluginConfigItemParamsWithTimeout creates a new DeletePluginConfigItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePluginConfigItemParamsWithTimeout(timeout time.Duration) *DeletePluginConfigItemParams {
	var ()
	return &DeletePluginConfigItemParams{

		timeout: timeout,
	}
}

// NewDeletePluginConfigItemParamsWithContext creates a new DeletePluginConfigItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePluginConfigItemParamsWithContext(ctx context.Context) *DeletePluginConfigItemParams {
	var ()
	return &DeletePluginConfigItemParams{

		Context: ctx,
	}
}

// NewDeletePluginConfigItemParamsWithHTTPClient creates a new DeletePluginConfigItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePluginConfigItemParamsWithHTTPClient(client *http.Client) *DeletePluginConfigItemParams {
	var ()
	return &DeletePluginConfigItemParams{
		HTTPClient: client,
	}
}

/*DeletePluginConfigItemParams contains all the parameters to send to the API endpoint
for the delete plugin config item operation typically these are written to a http.Request
*/
type DeletePluginConfigItemParams struct {

	/*Config*/
	Config []string
	/*Pname*/
	Pname string
	/*Ptype*/
	Ptype string
	/*Pversion*/
	Pversion int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithTimeout(timeout time.Duration) *DeletePluginConfigItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithContext(ctx context.Context) *DeletePluginConfigItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithHTTPClient(client *http.Client) *DeletePluginConfigItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfig adds the config to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithConfig(config []string) *DeletePluginConfigItemParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetConfig(config []string) {
	o.Config = config
}

// WithPname adds the pname to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithPname(pname string) *DeletePluginConfigItemParams {
	o.SetPname(pname)
	return o
}

// SetPname adds the pname to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetPname(pname string) {
	o.Pname = pname
}

// WithPtype adds the ptype to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithPtype(ptype string) *DeletePluginConfigItemParams {
	o.SetPtype(ptype)
	return o
}

// SetPtype adds the ptype to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetPtype(ptype string) {
	o.Ptype = ptype
}

// WithPversion adds the pversion to the delete plugin config item params
func (o *DeletePluginConfigItemParams) WithPversion(pversion int64) *DeletePluginConfigItemParams {
	o.SetPversion(pversion)
	return o
}

// SetPversion adds the pversion to the delete plugin config item params
func (o *DeletePluginConfigItemParams) SetPversion(pversion int64) {
	o.Pversion = pversion
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePluginConfigItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesConfig := o.Config

	joinedConfig := swag.JoinByFormat(valuesConfig, "")
	// form array param config
	if err := r.SetFormParam("config", joinedConfig...); err != nil {
		return err
	}

	// path param pname
	if err := r.SetPathParam("pname", o.Pname); err != nil {
		return err
	}

	// path param ptype
	if err := r.SetPathParam("ptype", o.Ptype); err != nil {
		return err
	}

	// path param pversion
	if err := r.SetPathParam("pversion", swag.FormatInt64(o.Pversion)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
