/*
http://www.apache.org/licenses/LICENSE-2.0.txt


Copyright 2017 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intelsdi-x/snap-client-go/models"
)

// GetPluginConfigItemReader is a Reader for the GetPluginConfigItem structure.
type GetPluginConfigItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPluginConfigItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPluginConfigItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetPluginConfigItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetPluginConfigItemUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPluginConfigItemOK creates a GetPluginConfigItemOK with default headers values
func NewGetPluginConfigItemOK() *GetPluginConfigItemOK {
	return &GetPluginConfigItemOK{}
}

/*GetPluginConfigItemOK handles this case with default header values.

PluginConfigResponse represents the response of a plugin config items.
*/
type GetPluginConfigItemOK struct {
	Payload models.ConfigDataNode
}

func (o *GetPluginConfigItemOK) Error() string {
	return fmt.Sprintf("[GET /plugins/{ptype}/{pname}/{pversion}/config][%d] getPluginConfigItemOK  %+v", 200, o.Payload)
}

func (o *GetPluginConfigItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPluginConfigItemBadRequest creates a GetPluginConfigItemBadRequest with default headers values
func NewGetPluginConfigItemBadRequest() *GetPluginConfigItemBadRequest {
	return &GetPluginConfigItemBadRequest{}
}

/*GetPluginConfigItemBadRequest handles this case with default header values.

ErrorResponse represents the Snap error response type.

It includes an error message and a map of fields.
*/
type GetPluginConfigItemBadRequest struct {
	Payload *models.Error
}

func (o *GetPluginConfigItemBadRequest) Error() string {
	return fmt.Sprintf("[GET /plugins/{ptype}/{pname}/{pversion}/config][%d] getPluginConfigItemBadRequest  %+v", 400, o.Payload)
}

func (o *GetPluginConfigItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPluginConfigItemUnauthorized creates a GetPluginConfigItemUnauthorized with default headers values
func NewGetPluginConfigItemUnauthorized() *GetPluginConfigItemUnauthorized {
	return &GetPluginConfigItemUnauthorized{}
}

/*GetPluginConfigItemUnauthorized handles this case with default header values.

UnauthResponse returns Unauthorized error struct message.
*/
type GetPluginConfigItemUnauthorized struct {
	Payload *models.UnauthError
}

func (o *GetPluginConfigItemUnauthorized) Error() string {
	return fmt.Sprintf("[GET /plugins/{ptype}/{pname}/{pversion}/config][%d] getPluginConfigItemUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPluginConfigItemUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
