package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intelsdi-x/snap-client-go/models"
)

// DeletePluginConfigItemReader is a Reader for the DeletePluginConfigItem structure.
type DeletePluginConfigItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePluginConfigItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePluginConfigItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePluginConfigItemOK creates a DeletePluginConfigItemOK with default headers values
func NewDeletePluginConfigItemOK() *DeletePluginConfigItemOK {
	return &DeletePluginConfigItemOK{}
}

/*DeletePluginConfigItemOK handles this case with default header values.

PluginConfigItem represents cdata.ConfigDataNode which implements it's own UnmarshalJSON.
*/
type DeletePluginConfigItemOK struct {
	Payload models.ConfigDataNode
}

func (o *DeletePluginConfigItemOK) Error() string {
	return fmt.Sprintf("[DELETE /plugins/{ptype}/{pname}/{pversion}/config][%d] deletePluginConfigItemOK  %+v", 200, o.Payload)
}

func (o *DeletePluginConfigItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
