package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePluginConfigItemReader is a Reader for the DeletePluginConfigItem structure.
type DeletePluginConfigItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePluginConfigItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePluginConfigItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeletePluginConfigItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePluginConfigItemOK creates a DeletePluginConfigItemOK with default headers values
func NewDeletePluginConfigItemOK() *DeletePluginConfigItemOK {
	return &DeletePluginConfigItemOK{}
}

/*DeletePluginConfigItemOK handles this case with default header values.

PluginConfigItem represents cdata.ConfigDataNode which implements it's own UnmarshalJSON.
*/
type DeletePluginConfigItemOK struct {
}

func (o *DeletePluginConfigItemOK) Error() string {
	return fmt.Sprintf("[DELETE /plugins/{ptype}/{pname}/{pversion}/config][%d] deletePluginConfigItemOK ", 200)
}

func (o *DeletePluginConfigItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePluginConfigItemBadRequest creates a DeletePluginConfigItemBadRequest with default headers values
func NewDeletePluginConfigItemBadRequest() *DeletePluginConfigItemBadRequest {
	return &DeletePluginConfigItemBadRequest{}
}

/*DeletePluginConfigItemBadRequest handles this case with default header values.

Error unsuccessful generic response to a failed API call
*/
type DeletePluginConfigItemBadRequest struct {
	Payload DeletePluginConfigItemBadRequestBody
}

func (o *DeletePluginConfigItemBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /plugins/{ptype}/{pname}/{pversion}/config][%d] deletePluginConfigItemBadRequest  %+v", 400, o.Payload)
}

func (o *DeletePluginConfigItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeletePluginConfigItemBadRequestBody delete plugin config item bad request body
swagger:model DeletePluginConfigItemBadRequestBody
*/
type DeletePluginConfigItemBadRequestBody map[string]string

// Validate validates this delete plugin config item bad request body
func (o DeletePluginConfigItemBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if swag.IsZero(o) { // not required
		return nil
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
