package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intelsdi-x/snap-client-go/models"
)

// GetPluginsReader is a Reader for the GetPlugins structure.
type GetPluginsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPluginsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPluginsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPluginsOK creates a GetPluginsOK with default headers values
func NewGetPluginsOK() *GetPluginsOK {
	return &GetPluginsOK{}
}

/*GetPluginsOK handles this case with default header values.

PluginsResp represents the response from plugin operations.
*/
type GetPluginsOK struct {
	Payload GetPluginsOKBody
}

func (o *GetPluginsOK) Error() string {
	return fmt.Sprintf("[GET /plugins][%d] getPluginsOK  %+v", 200, o.Payload)
}

func (o *GetPluginsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPluginsOKBody get plugins o k body
swagger:model GetPluginsOKBody
*/
type GetPluginsOKBody struct {

	// plugins
	// Required: true
	Plugins []*models.Plugin `json:"Plugins"`
}

// Validate validates this get plugins o k body
func (o *GetPluginsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePlugins(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPluginsOKBody) validatePlugins(formats strfmt.Registry) error {

	if err := validate.Required("getPluginsOK"+"."+"plugins", "body", o.Plugins); err != nil {
		return err
	}

	for i := 0; i < len(o.Plugins); i++ {

		if swag.IsZero(o.Plugins[i]) { // not required
			continue
		}

		if o.Plugins[i] != nil {

			if err := o.Plugins[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPluginsOK" + "." + "plugins" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}
