package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intelsdi-x/snap-client-go/models"
)

// SetPluginConfigItemReader is a Reader for the SetPluginConfigItem structure.
type SetPluginConfigItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPluginConfigItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetPluginConfigItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPluginConfigItemOK creates a SetPluginConfigItemOK with default headers values
func NewSetPluginConfigItemOK() *SetPluginConfigItemOK {
	return &SetPluginConfigItemOK{}
}

/*SetPluginConfigItemOK handles this case with default header values.

PluginConfigItem represents cdata.ConfigDataNode which implements it's own UnmarshalJSON.
*/
type SetPluginConfigItemOK struct {
	Payload models.ConfigDataNode
}

func (o *SetPluginConfigItemOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/{ptype}/{pname}/{pversion}/config][%d] setPluginConfigItemOK  %+v", 200, o.Payload)
}

func (o *SetPluginConfigItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
