// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ConfigDataNode Represents a set of configuration data
// swagger:model ConfigDataNode
type ConfigDataNode interface{}
