package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DynamicElement DynamicElement defines the dynamic element of a metric.
// swagger:model DynamicElement
type DynamicElement struct {

	// description
	Description string `json:"Description,omitempty"`

	// index
	Index int64 `json:"Index,omitempty"`

	// name
	// Required: true
	Name *string `json:"Name"`
}

// Validate validates this dynamic element
func (m *DynamicElement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DynamicElement) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}
