package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Plugin Plugin represents a plugin type definition.
// swagger:model Plugin
type Plugin struct {

	// config policy
	ConfigPolicy []PolicyTable `json:"config_policy"`

	// hitcount
	Hitcount int64 `json:"hitcount,omitempty"`

	// href
	Href string `json:"href,omitempty"`

	// id
	ID uint32 `json:"id,omitempty"`

	// last hit timestamp
	LastHitTimestamp int64 `json:"last_hit_timestamp,omitempty"`

	// loaded timestamp
	LoadedTimestamp int64 `json:"loaded_timestamp,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pprof port
	PprofPort string `json:"pprof_port,omitempty"`

	// signed
	Signed bool `json:"signed,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

// Validate validates this plugin
func (m *Plugin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfigPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plugin) validateConfigPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.ConfigPolicy) { // not required
		return nil
	}

	return nil
}
