// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PolicyTable policy table
// swagger:model PolicyTable
type PolicyTable struct {
	RuleTable
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PolicyTable) UnmarshalJSON(raw []byte) error {

	var aO0 RuleTable
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.RuleTable = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PolicyTable) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.RuleTable)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this policy table
func (m *PolicyTable) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.RuleTable.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyTable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyTable) UnmarshalBinary(b []byte) error {
	var res PolicyTable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
