package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessWorkflowMapNode process workflow map node
// swagger:model ProcessWorkflowMapNode
type ProcessWorkflowMapNode struct {

	// TODO processor config
	Config map[string]interface{} `json:"Config,omitempty"`

	// name
	// Required: true
	Name *string `json:"Name"`

	// process
	// Required: true
	Process []*ProcessWorkflowMapNode `json:"Process"`

	// publish
	// Required: true
	Publish []*PublishWorkflowMapNode `json:"Publish"`

	// target
	Target string `json:"Target,omitempty"`

	// version
	Version int64 `json:"Version,omitempty"`
}

// Validate validates this process workflow map node
func (m *ProcessWorkflowMapNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateProcess(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePublish(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessWorkflowMapNode) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ProcessWorkflowMapNode) validateProcess(formats strfmt.Registry) error {

	if err := validate.Required("process", "body", m.Process); err != nil {
		return err
	}

	for i := 0; i < len(m.Process); i++ {

		if swag.IsZero(m.Process[i]) { // not required
			continue
		}

		if m.Process[i] != nil {

			if err := m.Process[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("process" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProcessWorkflowMapNode) validatePublish(formats strfmt.Registry) error {

	if err := validate.Required("publish", "body", m.Publish); err != nil {
		return err
	}

	for i := 0; i < len(m.Publish); i++ {

		if swag.IsZero(m.Publish[i]) { // not required
			continue
		}

		if m.Publish[i] != nil {

			if err := m.Publish[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("publish" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}
