/*
http://www.apache.org/licenses/LICENSE-2.0.txt


Copyright 2017 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublishWorkflowMapNode publish workflow map node
// swagger:model PublishWorkflowMapNode
type PublishWorkflowMapNode struct {

	// config
	// Required: true
	Config map[string]interface{} `json:"config"`

	// plugin name
	// Required: true
	PluginName *string `json:"plugin_name"`

	// plugin version
	PluginVersion int64 `json:"plugin_version,omitempty"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this publish workflow map node
func (m *PublishWorkflowMapNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePluginName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublishWorkflowMapNode) validateConfig(formats strfmt.Registry) error {

	if err := validate.Required("config", "body", m.Config); err != nil {
		return err
	}

	return nil
}

func (m *PublishWorkflowMapNode) validatePluginName(formats strfmt.Registry) error {

	if err := validate.Required("plugin_name", "body", m.PluginName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublishWorkflowMapNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublishWorkflowMapNode) UnmarshalBinary(b []byte) error {
	var res PublishWorkflowMapNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
