// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StreamedMetric streamed metric
// swagger:model StreamedMetric
type StreamedMetric struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`

	// timestamp
	Timestamp interface{} `json:"timestamp,omitempty"`
}

// Validate validates this streamed metric
func (m *StreamedMetric) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StreamedMetric) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StreamedMetric) UnmarshalBinary(b []byte) error {
	var res StreamedMetric
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
