package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// StreamedTaskEvent StreamedTaskEvent defines the task watching data type.
// swagger:model StreamedTaskEvent
type StreamedTaskEvent struct {

	// event
	Event StreamedMetrics `json:"event"`

	// message
	Message string `json:"message,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this streamed task event
func (m *StreamedTaskEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
