package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StreamedTaskEvent StreamedTaskEvent defines the task watching data type.
// swagger:model StreamedTaskEvent
type StreamedTaskEvent struct {

	// event type
	EventType string `json:"type,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// event
	Event StreamedMetrics `json:"event"`
}

// Validate validates this streamed task event
func (m *StreamedTaskEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StreamedTaskEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StreamedTaskEvent) UnmarshalBinary(b []byte) error {
	var res StreamedTaskEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
