package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// WorkflowMap WorkflowMap A map of a desired workflow that is used to create a scheduleWorkflow
// swagger:model WorkflowMap
type WorkflowMap struct {

	// collect
	// Required: true
	Collect *CollectWorkflowMapNode `json:"collect"`
}

// Validate validates this workflow map
func (m *WorkflowMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollect(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowMap) validateCollect(formats strfmt.Registry) error {

	if err := validate.Required("collect", "body", m.Collect); err != nil {
		return err
	}

	if m.Collect != nil {

		if err := m.Collect.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("collect")
			}
			return err
		}
	}

	return nil
}
